# implement your solution in exercise 2.1 here

version: '3.8'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    volumes:
      - ./logs/text.log:/usr/src/app/text.log
