# This Docker compose file is needed in exercise 2.5
# You should not need to modify this file.
#
# See the readme at https://github.com/docker-hy/material-applications/tree/main/scaling-exercise
# This exercise was created with [Sasu Mäkinen](https://github.com/sasumaki)

version: '3.2'

services:
  # calculator is the "frontend"
  calculator:
    image: devopsdockeruh/scaling-exercise-calculator
    ports:
      - 3000:3000
    container_name: calculator

  # compute is the "backend"
  compute:
    image: devopsdockeruh/scaling-exercise-compute
    environment:
      - VIRTUAL_HOST=compute.localtest.me

  # the load balancer should share the load from the frontend across multiple backend containers
  load-balancer:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80

    # all requests are handled by the compute service by default
    environment:
      - DEFAULT_HOST=compute.localtest.me

    container_name: load-balancer
